# Generated by Django 3.1 on 2020-09-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200905_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listings',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(),
        ),
    ]
